spring.application.name=tradewise-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/papertrade
spring.datasource.username=postgres
spring.datasource.password=Aryan123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TradeWiseDevelopmentSecretKey12345678901234567890
jwt.expiration=900000